kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
- role: worker
- role: worker
kubeadmConfigPatches:
- |
  kind: InitConfiguration
  nodeRegistration:
    kubeletExtraArgs:
      "system-reserved": "memory=8Gi"   # Solicita memória do sistema
      "kube-reserved": "memory=4Gi"     # Solicita memória do Kubernetes