apiVersion: apps/v1
kind: Deployment
metadata:
  name: pyserver
spec:
  selector:
    matchLabels:
      app: pyserver
  template:
    metadata:
      labels:
        app: apicomentario
    spec:
      containers:
      - name: pyserver
        image: pyserver
        ports:
        - containerPort: 8000