apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml

images:
- name: pyserver
  newName: uzedmaster/apicomentario
  newTag: d6932f888825afbe96836633855f22e6e4242f0b
