filebeat:
  filebeatConfig:
    filebeat.yml: |
      filebeat.inputs:
      - type: container
        paths:
          - /var/log/containers/pyserver*.log
        processors:
          - add_kubernetes_metadata:
              in_cluster: true

      output.elasticsearch:
        hosts: ["http://elasticsearch-master:9200"]
        username: "kibanaadmin"
        password: "kibanabana"
      

      setup.kibana:
        host: "kibana-kibana:5601"
        username: "kibanaadmin"
        password: "kibanabana"
    
      setup.dashboards.enabled: true